server:
  port: 8080

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**, /api/seniors/**, /api/companies/**, /api/preparation/**, /api/applications/**

        - id: mentorship-service
          uri: lb://MENTORSHIP-SERVICE
          predicates:
            - Path=/api/mentorship/**, /api/sessions/**, /api/chat/**, /api/reviews/**

        - id: interview-service
          uri: lb://INTERVIEW-SERVICE
          predicates:
            - Path=/api/interviews/**, /api/mock-interviews/**, /api/resume-reviews/**

        - id: resource-service
          uri: lb://RESOURCE-SERVICE
          predicates:
            - Path=/api/resources/**

        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/notifications/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
